export const BOARD_SIZE = 10;

export const SET_BOARD_SIZE = 'SET_BOARD_SIZE';
export const SET_BOARD = 'SET_BOARD';
export const SET_PLAYERS = 'SET_PLAYERS';
export const SET_LEADERBOARD = 'SET_LEADERBOARD';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_IS_GAME_RUNNING = 'SET_IS_GAME_RUNNING';
export const INCREMENT_CHECKED_BLOCKS = 'INCREMENT_CHECKED_BLOCKS';
export const SET_WINNER = 'SET_WINNER';
